services:
  app:
    container_name: fastapi-contianer
    build:
      context: ./dockerfile
      dockerfile: Dockerfile.fastapi
    env_file: ./backend/.env

    command: python3.10 -m uvicorn main:app --reload --host 0.0.0.0 --port 8888
    volumes:
      - type: bind
        target: .
        source: /code/
    ports:
      - target: 8888
        published: 8888

  db:
    build:
      context: ./dockerfile
      dockerfile: Dockerfile.postgresql
    env_file: ./db/.env
    volumes:
      - type: volume
        source: test-db
        target: /var/lib/postgresql/data
    ports:
      - published: 5432
        target: 5432

volumes:
  test-db:
