services:
  app:
    container_name: fastapi-contianer
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env

    working_dir: /code/
    command: python3.10 -m uvicorn api.main:app --reload --host 0.0.0.0 --port 8888

    volumes:
      - type: bind
        source: ./backend
        target: /code
    ports:
      - target: 8888
        published: 8888
    depends_on:
      db:
        condition: service_started

  db:
    container_name: fastapi-postgre
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file: ./db/.env

    volumes:
      - type: volume
        source: postgres-volume
        target: /var/lib/postgresql/data

    ports:
      - published: 5432
        target: 5432

volumes:
  postgres-volume:
    name: 19-fastapi-sqlalchemy-postgres-data
