services:
  app:
    container_name: fastapi-container
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env

    working_dir: /api/
    command: python3.10 -m uvicorn api.main:app --reload --host 0.0.0.0 --port 8888

    volumes:
      - type: bind
        source: ./backend
        target: /api
    ports:
      - target: 8888
        published: 8888
    depends_on:
      db:
        condition: service_started

  db:
    container_name: fastapi-postgre
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file: ./db/.env
    volumes:
      - type: volume
        source: postgres-volume
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - target: 5432
        published: 5432

volumes:
  postgres-volume:
    name: 19-fastapi-sqlalchemy-postgres-data
